FROM ubuntu:16.04

MAINTAINER Mohit_Sharma <mohit.sharma@nyu.edu>

# Update the index of available packages.
RUN apt-get update

# Install the requires apt package and python.
RUN apt-get install -y --no-install-recommends \
      linux-headers-generic gcc build-essential python python-pip python-dev \
      python3-dev python3-pip \
      libffi-dev \
      && \
      apt-get clean

# Setup the ansible.
RUN apt-get install -y --no-install-recommends \
      python-software-properties software-properties-common

RUN add-apt-repository ppa:ansible/ansible -y && apt-get update

RUN apt-get install -y --no-install-recommends \
      ansible \
      && \
      apt-get clean

# for disable localhost warning message.
RUN /bin/echo -e "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

WORKDIR /home/notebooks

# Upgrade the pip to lastest.
RUN pip install -U pip

# Setup with Ansible.
ADD https://raw.githubusercontent.com/hk1953/ucsl-image/master/image/jupyter.yml /home
RUN ansible-playbook -vvvv /home/jupyter.yml

# Run service of Jupyter.
COPY start-notebook.sh /usr/local/bin/
ENTRYPOINT [ "start-notebook.sh" ]

# Print the version of jupyter that has been started
CMD [ "jupyter", "--version" ]